# Generated by Django 5.2 on 2025-04-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='descrição',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='nome',
            new_name='nome_produto',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='preço',
            new_name='preco',
        ),
        migrations.AddField(
            model_name='categoria',
            name='descricao',
            field=models.CharField(default='', max_length=100),
        ),
    ]
