# Generated by Django 5.2 on 2025-04-09 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0002_rename_descrição_produto_descricao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='descricao',
        ),
    ]
